# Generated by Django 5.1.7 on 2025-03-24 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0005_recipeimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RecipeImage',
        ),
    ]
