# Generated by Django 5.1.7 on 2025-03-24 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0008_alter_recipeimage_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipeimage',
            old_name='image',
            new_name='recipe_image',
        ),
        migrations.AlterField(
            model_name='recipeimage',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='ledger.recipe'),
        ),
    ]
